#!/bin/bash
cd /home/asus/Github/Sentrix-Home-Web
exec env SENTRIX_API_PORT=8096 SENTRIX_THIN_AGENT_V1=1 SENTRIX_EVIDENCE_MULTI_RETRIEVER_V1=1 \
  SENTRIX_IMAGE_EMBEDDER=chinese_clip SENTRIX_TEXT_EMBEDDER=clip SENTRIX_MODEL_SPLIT_V1=1 \
  SENTRIX_AGENT_MODEL_PROFILE=quality_12b SENTRIX_AGENT_STAGE_TRACE=1 CLIP_DEVICE=cpu \
  SENTRIX_LLM_BACKEND=ollama OLLAMA_BASE_URL=http://127.0.0.1:11434 OLLAMA_MODEL=gemma4:12b \
  SENTRIX_RX_V1=1 SENTRIX_ANSWER_BRIEF_V1=1 SENTRIX_RESPONSE_PLAN_V1=1 SENTRIX_VISIBLE_EVIDENCE_V1=1 \
  SENTRIX_RESPONSE_WRITER_V2=1 SENTRIX_RESPONSE_VALIDATOR_V1=1 SENTRIX_ADMIN_DEBUG_PRESENTATION=1 \
  SENTRIX_TASK_CONTRACT_V2=1 SENTRIX_RETRIEVAL_STRATEGY_V1=1 SENTRIX_STRUCTURED_MEMORY_V1=1 \
  PYTHONPATH=. .venv/bin/python -m uvicorn backend.app:app --host 127.0.0.1 --port 8096
