#!/bin/bash
# 12B full-chain validation API instance (port 8092, local only).
# NEVER the production 8091 — validation flags are on here only.
cd /home/asus/Github/Sentrix-Home-Web
exec env SENTRIX_API_PORT=8092 SENTRIX_THIN_AGENT_V1=1 SENTRIX_EVIDENCE_MULTI_RETRIEVER_V1=1 \
  SENTRIX_IMAGE_EMBEDDER=chinese_clip SENTRIX_TEXT_EMBEDDER=clip SENTRIX_MODEL_SPLIT_V1=1 \
  SENTRIX_AGENT_MODEL_PROFILE=quality_12b SENTRIX_AGENT_STAGE_TRACE=1 CLIP_DEVICE=cpu \
  SENTRIX_12B_FULL_CHAIN_VALIDATION=1 SENTRIX_AGENT_NO_FALLBACK=1 SENTRIX_AGENT_DISABLE_CACHE=1 \
  SENTRIX_AGENT_REQUIRE_MODEL_TRACE=1 SENTRIX_AGENT_REQUIRE_12B_ROLES=1 SENTRIX_AGENT_FAIL_ON_DEGRADATION=1 \
  PYTHONPATH=. .venv/bin/python -m uvicorn backend.app:app --host 127.0.0.1 --port 8092
