"""Derived MAGMA-style graph memory index for Sentrix.

This module deliberately owns only three derived tables in ``sentrix.db``.
The canonical memory tables (assets, observations, events, entities and
relationships) remain the source of truth and are never updated here.

The graph is deterministic and rebuildable.  Causal edges are part of the
schema vocabulary but are not generated by this first integration; a rebuild
therefore always writes zero causal edges.
"""

from __future__ import annotations

import hashlib
import json
import re
import sqlite3
import uuid
from collections import defaultdict, deque
from datetime import datetime, timezone


NODE_TYPES = frozenset({"EVENT", "SESSION", "EPISODE", "ENTITY"})
CAUSAL_EDGE_SUBTYPES = frozenset({"LEADS_TO", "ENABLES"})
DEFAULT_NODE_WEIGHTS = {"EVENT": 1.0, "SESSION": 0.85, "ENTITY": 0.9, "EPISODE": 0.65}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _json(value, fallback):
    if value is None:
        value = fallback
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _loads(value, fallback):
    if value in (None, ""):
        return fallback
    try:
        parsed = json.loads(value)
    except (TypeError, ValueError, json.JSONDecodeError):
        return fallback
    return parsed


def _stable_id(prefix: str, *parts: object) -> str:
    payload = "\x1f".join(str(part if part is not None else "") for part in parts)
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()[:32]
    return f"{prefix}_{digest}"


def _text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return str(value).strip()


def _join_text(*values) -> str:
    return " ".join(item for value in values if (item := _text(value)))


def _float(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _int(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _csv_or_list(value):
    if value is None:
        return []
    if isinstance(value, (list, tuple, set)):
        values = value
    else:
        values = str(value).split(",")
    return [str(item).strip().upper() for item in values if str(item).strip()]


class GraphMemoryService:
    """Build and query a deterministic, scope-isolated SQLite graph index."""

    def __init__(self, database):
        self._owns_connection = hasattr(database, "connection") is False
        if self._owns_connection:
            path = getattr(database, "path", database)
            self.db_path = str(path)
            self.connection = sqlite3.connect(self.db_path, timeout=30)
        else:
            self.db_path = str(getattr(database, "path", ""))
            self.connection = database.connection
        self.connection.row_factory = sqlite3.Row
        self.connection.execute("PRAGMA foreign_keys = ON")
        self.connection.execute("PRAGMA busy_timeout = 30000")

    def close(self):
        if self._owns_connection:
            self.connection.close()

    def __enter__(self):
        self.ensure_schema()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.close()

    def _rows(self, sql, params=()):
        return [dict(row) for row in self.connection.execute(sql, params).fetchall()]

    def _row(self, sql, params=()):
        row = self.connection.execute(sql, params).fetchone()
        return dict(row) if row else None

    def _table_exists(self, name):
        return bool(self._row("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (name,)))

    def ensure_schema(self):
        """Create only the three derived graph tables and their indexes."""
        self.connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS graph_memory_nodes (
                node_id TEXT PRIMARY KEY,
                scope_id TEXT NOT NULL,
                node_type TEXT NOT NULL,
                source_type TEXT NOT NULL,
                source_id TEXT NOT NULL,
                title TEXT NOT NULL DEFAULT '',
                content TEXT NOT NULL DEFAULT '',
                time_start TEXT,
                time_end TEXT,
                attributes_json TEXT NOT NULL DEFAULT '{}',
                search_text TEXT NOT NULL DEFAULT '',
                source_revision TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE(scope_id, source_type, source_id)
            );
            CREATE TABLE IF NOT EXISTS graph_memory_edges (
                edge_id TEXT PRIMARY KEY,
                scope_id TEXT NOT NULL,
                source_node_id TEXT NOT NULL,
                target_node_id TEXT NOT NULL,
                edge_type TEXT NOT NULL,
                edge_subtype TEXT NOT NULL DEFAULT '',
                confidence REAL NOT NULL DEFAULT 1.0,
                reason TEXT NOT NULL DEFAULT '',
                attributes_json TEXT NOT NULL DEFAULT '{}',
                source_revision TEXT NOT NULL DEFAULT '',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS graph_memory_builds (
                build_id TEXT PRIMARY KEY,
                scope_id TEXT NOT NULL,
                status TEXT NOT NULL,
                source_revision TEXT NOT NULL DEFAULT '',
                stats_json TEXT NOT NULL DEFAULT '{}',
                error TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                finished_at TEXT
            );
            CREATE INDEX IF NOT EXISTS idx_graph_nodes_scope_type
                ON graph_memory_nodes(scope_id, node_type);
            CREATE INDEX IF NOT EXISTS idx_graph_nodes_scope_source
                ON graph_memory_nodes(scope_id, source_type, source_id);
            CREATE INDEX IF NOT EXISTS idx_graph_nodes_search
                ON graph_memory_nodes(scope_id, search_text);
            CREATE INDEX IF NOT EXISTS idx_graph_edges_scope_source
                ON graph_memory_edges(scope_id, source_node_id);
            CREATE INDEX IF NOT EXISTS idx_graph_edges_scope_target
                ON graph_memory_edges(scope_id, target_node_id);
            CREATE INDEX IF NOT EXISTS idx_graph_edges_scope_type
                ON graph_memory_edges(scope_id, edge_type, edge_subtype);
            CREATE INDEX IF NOT EXISTS idx_graph_builds_scope_time
                ON graph_memory_builds(scope_id, created_at DESC);
            """
        )
        self.connection.commit()

    def _source_revision(self, scope_id):
        """Return a compact source snapshot marker without mutating canonical data."""
        pieces = []
        for table in ("assets", "observations", "events", "entities", "relationships"):
            if not self._table_exists(table):
                pieces.append(f"{table}:missing")
                continue
            columns = {row["name"] for row in self.connection.execute(f"PRAGMA table_info({table})")}
            scope_clause = " WHERE scope_id = ?" if "scope_id" in columns else ""
            params = (scope_id,) if scope_clause else ()
            count = self._row(f"SELECT COUNT(*) AS n FROM {table}{scope_clause}", params)["n"]
            revision = ""
            if "revision" in columns:
                row = self._row(f"SELECT MAX(revision) AS v FROM {table}{scope_clause}", params)
                revision = str(row["v"] or "")
            if "updated_at" in columns:
                row = self._row(f"SELECT MAX(updated_at) AS v FROM {table}{scope_clause}", params)
                revision = f"{revision}:{row['v'] or ''}"
            pieces.append(f"{table}:{count}:{revision}")
        link_snapshots = (
            ("event_observations", "SELECT COUNT(*) AS n FROM event_observations eo JOIN events e ON e.id = eo.event_id WHERE e.scope_id = ?"),
            ("entity_observations", "SELECT COUNT(*) AS n FROM entity_observations eo JOIN entities e ON e.id = eo.entity_id WHERE e.scope_id = ?"),
            ("entity_mentions", "SELECT COUNT(*) AS n FROM entity_mentions em JOIN entities e ON e.id = em.entity_id WHERE e.scope_id = ?"),
            ("event_entities", "SELECT COUNT(*) AS n FROM event_entities ee JOIN events e ON e.id = ee.event_id JOIN entities en ON en.id = ee.entity_id WHERE e.scope_id = ? AND en.scope_id = ?"),
        )
        for table, sql in link_snapshots:
            if self._table_exists(table):
                params = (scope_id, scope_id) if table == "event_entities" else (scope_id,)
                count = self._row(sql, params)["n"]
                pieces.append(f"{table}:{count}")
        return "|".join(pieces)

    @staticmethod
    def _node_id(scope_id, source_type, source_id):
        return _stable_id("gm_node", scope_id, source_type, source_id)

    @staticmethod
    def _edge_id(scope_id, source_id, target_id, edge_type, edge_subtype, discriminator=""):
        return _stable_id("gm_edge", scope_id, source_id, target_id, edge_type, edge_subtype, discriminator)

    @staticmethod
    def _source_row_revision(row):
        return str(row.get("revision") or row.get("updated_at") or row.get("created_at") or "")

    def _add_node(self, nodes, scope_id, node_type, source_type, source_id, title="", content="",
                  time_start=None, time_end=None, attributes=None, search_text="", source_revision=""):
        node_id = self._node_id(scope_id, source_type, source_id)
        attrs = dict(attributes or {})
        attrs.setdefault("scope_id", scope_id)
        attrs.setdefault("source_type", source_type)
        attrs.setdefault("source_id", source_id)
        nodes[node_id] = {
            "node_id": node_id, "scope_id": scope_id, "node_type": node_type,
            "source_type": source_type, "source_id": str(source_id),
            "title": _text(title), "content": _text(content),
            "time_start": time_start, "time_end": time_end,
            "attributes_json": _json(attrs, {}),
            "search_text": _join_text(title, content, search_text).casefold(),
            "source_revision": str(source_revision or ""),
        }
        return node_id

    def _add_edge(self, edges, scope_id, source_node_id, target_node_id, edge_type,
                  edge_subtype="", confidence=1.0, reason="", attributes=None,
                  source_revision="", discriminator=""):
        if not source_node_id or not target_node_id or source_node_id == target_node_id:
            return None
        subtype = str(edge_subtype or "")
        edge_id = self._edge_id(scope_id, source_node_id, target_node_id, edge_type, subtype, discriminator)
        edges[edge_id] = {
            "edge_id": edge_id, "scope_id": scope_id,
            "source_node_id": source_node_id, "target_node_id": target_node_id,
            "edge_type": str(edge_type), "edge_subtype": subtype,
            "confidence": max(0.0, min(1.0, float(confidence or 0))),
            "reason": _text(reason), "attributes_json": _json(attributes or {}, {}),
            "source_revision": str(source_revision or ""),
        }
        return edge_id

    def _load_source(self, scope_id):
        assets = self._rows("SELECT * FROM assets WHERE scope_id = ? ORDER BY created_at, id", (scope_id,)) if self._table_exists("assets") else []
        observations = self._rows("SELECT o.*, a.file_name AS asset_file_name, a.media_type AS asset_media_type, a.captured_at AS asset_captured_at, a.parent_asset_id, a.derived_kind, a.source_timestamp_sec, a.source_frame_index, a.source_scene_index FROM observations o JOIN assets a ON a.id = o.asset_id WHERE o.scope_id = ? ORDER BY o.created_at, o.id", (scope_id,)) if self._table_exists("observations") else []
        events = self._rows("SELECT * FROM events WHERE scope_id = ? ORDER BY created_at, id", (scope_id,)) if self._table_exists("events") else []
        entities = self._rows("SELECT * FROM entities WHERE scope_id = ? ORDER BY created_at, id", (scope_id,)) if self._table_exists("entities") else []
        event_observations = self._rows("SELECT eo.* FROM event_observations eo JOIN events e ON e.id = eo.event_id WHERE e.scope_id = ? ORDER BY eo.event_id, eo.observation_id", (scope_id,)) if self._table_exists("event_observations") else []
        entity_observations = self._rows("SELECT eob.* FROM entity_observations eob JOIN entities e ON e.id = eob.entity_id WHERE e.scope_id = ? ORDER BY eob.entity_id, eob.observation_id", (scope_id,)) if self._table_exists("entity_observations") else []
        entity_mentions = self._rows("SELECT em.* FROM entity_mentions em JOIN entities e ON e.id = em.entity_id WHERE e.scope_id = ? ORDER BY em.entity_id, em.observation_id, em.id", (scope_id,)) if self._table_exists("entity_mentions") else []
        event_entities = self._rows("SELECT ee.* FROM event_entities ee JOIN events ev ON ev.id = ee.event_id JOIN entities en ON en.id = ee.entity_id WHERE ev.scope_id = ? AND en.scope_id = ? ORDER BY ee.event_id, ee.entity_id, ee.relation", (scope_id, scope_id)) if self._table_exists("event_entities") else []
        relationships = self._rows("SELECT * FROM relationships WHERE scope_id = ? ORDER BY created_at, id", (scope_id,)) if self._table_exists("relationships") else []
        return {
            "assets": assets, "observations": observations, "events": events,
            "entities": entities, "event_observations": event_observations,
            "entity_observations": entity_observations, "entity_mentions": entity_mentions,
            "event_entities": event_entities, "relationships": relationships,
        }

    def _build_rows(self, scope_id):
        source = self._load_source(scope_id)
        nodes = {}
        edges = {}
        source_revision = self._source_revision(scope_id)
        node_by_source = {}

        def add(*args, **kwargs):
            node_id = self._add_node(nodes, *args, **kwargs)
            node_by_source[(args[2], args[3])] = node_id
            return node_id

        # Every scope has a stable EPISODE root for non-video events.
        root_id = add(scope_id, "EPISODE", "memory_space", scope_id,
                      title=scope_id, content="MemorySpace root",
                      attributes={"scope_id": scope_id, "memory_space_id": scope_id},
                      search_text=scope_id, source_revision=source_revision)

        assets_by_id = {row["id"]: row for row in source["assets"]}
        video_episode_ids = {}
        for asset in source["assets"]:
            if asset.get("media_type") != "video" or asset.get("parent_asset_id") or asset.get("derived_kind"):
                continue
            video_episode_ids[asset["id"]] = add(
                scope_id, "EPISODE", "asset", asset["id"],
                title=asset.get("file_name") or asset["id"],
                content=_join_text(asset.get("file_name"), asset.get("captured_location")),
                time_start=asset.get("captured_at"), time_end=asset.get("captured_at"),
                attributes={"asset_id": asset["id"], "media_type": asset.get("media_type"), "scope_id": scope_id},
                search_text=asset.get("file_name"), source_revision=self._source_row_revision(asset),
            )

        event_observation_ids = defaultdict(list)
        for row in source["event_observations"]:
            event_observation_ids[row["event_id"]].append(row["observation_id"])
        event_by_id = {row["id"]: row for row in source["events"]}
        observation_by_id = {row["id"]: row for row in source["observations"]}

        for event in source["events"]:
            event_id = add(
                scope_id, "SESSION", "event", event["id"],
                title=event.get("title") or event.get("activity") or event["id"],
                content=_join_text(event.get("summary"), event.get("activity"), event.get("place"), event.get("event_type")),
                time_start=event.get("time_start"), time_end=event.get("time_end"),
                attributes={"event_id": event["id"], "scope_id": scope_id, "source_type": event.get("source_type"), "source_asset_id": event.get("source_asset_id"), "source_scene_index": event.get("source_scene_index")},
                search_text=_join_text(event.get("participants_json"), event.get("source_metadata_json")),
                source_revision=self._source_row_revision(event),
            )
            episode_id = video_episode_ids.get(event.get("source_asset_id"), root_id)
            if episode_id == root_id:
                for observation_id in event_observation_ids.get(event["id"], []):
                    obs = observation_by_id.get(observation_id) or {}
                    asset = assets_by_id.get(obs.get("asset_id")) or {}
                    episode_id = video_episode_ids.get(asset.get("parent_asset_id"), episode_id)
                    if episode_id != root_id:
                        break
            self._add_edge(edges, scope_id, event_id, episode_id, "SEMANTIC", "PART_OF", 1.0,
                           "canonical event/source asset", {"event_id": event["id"], "asset_id": event.get("source_asset_id")}, self._source_row_revision(event))

        for observation in source["observations"]:
            content = _join_text(
                observation.get("caption"), observation.get("activity"), observation.get("place"),
                observation.get("transcript"), observation.get("ocr_text"), observation.get("event_type"),
                _loads(observation.get("objects_json"), []), _loads(observation.get("spatial_relations_json"), []),
            )
            attrs = {
                "observation_id": observation["id"], "asset_id": observation.get("asset_id"),
                "scope_id": scope_id, "source_type": observation.get("source_type"),
                "source_timestamp_sec": observation.get("source_timestamp_sec"),
                "source_frame_index": observation.get("source_frame_index"),
                "source_scene_index": observation.get("source_scene_index"),
            }
            event_ids = [row["event_id"] for row in source["event_observations"] if row["observation_id"] == observation["id"]]
            attrs["event_id"] = event_ids[0] if len(event_ids) == 1 else event_ids
            add(scope_id, "EVENT", "observation", observation["id"],
                title=observation.get("caption") or observation.get("activity") or observation.get("asset_file_name") or observation["id"],
                content=content, time_start=observation.get("captured_at") or observation.get("asset_captured_at"),
                time_end=observation.get("captured_at") or observation.get("asset_captured_at"),
                attributes=attrs, search_text=content, source_revision=self._source_row_revision(observation))

        for entity in source["entities"]:
            add(scope_id, "ENTITY", "entity", entity["id"],
                title=entity.get("canonical_name") or entity["id"],
                content=_join_text(entity.get("summary"), entity.get("family_role"), entity.get("entity_type")),
                attributes={"entity_id": entity["id"], "entity_type": entity.get("entity_type"), "status": entity.get("status"), "scope_id": scope_id},
                search_text=entity.get("canonical_name"), source_revision=self._source_row_revision(entity))

        for row in source["event_observations"]:
            self._add_edge(
                edges, scope_id, node_by_source.get(("observation", row["observation_id"])),
                node_by_source.get(("event", row["event_id"])), "SEMANTIC", "BELONGS_TO_SESSION", 1.0,
                "event_observations", {"observation_id": row["observation_id"], "event_id": row["event_id"]},
                self._source_row_revision(event_by_id.get(row["event_id"], {})), row["observation_id"],
            )

        # Observation order is based on source timestamp first, then captured
        # time and source frame index.  Only the forward edge is materialized.
        for event_id, observation_ids in event_observation_ids.items():
            rows = [observation_by_id[item] for item in observation_ids if item in observation_by_id]
            rows.sort(key=lambda row: (
                _float(row.get("source_timestamp_sec")) is None,
                _float(row.get("source_timestamp_sec")) or 0.0,
                str(row.get("captured_at") or row.get("asset_captured_at") or ""),
                _int(row.get("source_frame_index")) is None,
                _int(row.get("source_frame_index")) or 0,
                str(row.get("id")),
            ))
            for previous, current in zip(rows, rows[1:]):
                self._add_edge(edges, scope_id, node_by_source.get(("observation", previous["id"])), node_by_source.get(("observation", current["id"])), "TEMPORAL", "PRECEDES", 1.0, "observation order", {"ordering_scope": "event", "event_id": event_id}, self._source_row_revision(current), event_id)

        # Scene order is scoped to the original video asset and does not turn
        # adjacency into causality.
        scenes_by_video = defaultdict(list)
        for event in source["events"]:
            if event.get("source_type") == "video_scene" and event.get("source_asset_id") in video_episode_ids:
                scenes_by_video[event["source_asset_id"]].append(event)
        for video_id, scenes in scenes_by_video.items():
            scenes.sort(key=lambda row: (
                _int(row.get("source_scene_index")) is None,
                _int(row.get("source_scene_index")) or 0,
                _float(row.get("source_start_sec")) is None,
                _float(row.get("source_start_sec")) or 0.0,
                str(row.get("id")),
            ))
            for previous, current in zip(scenes, scenes[1:]):
                self._add_edge(edges, scope_id, node_by_source.get(("event", previous["id"])), node_by_source.get(("event", current["id"])), "TEMPORAL", "PRECEDES", 1.0, "scene order", {"ordering_scope": "scene", "asset_id": video_id}, self._source_row_revision(current), video_id)

        for row in source["entity_observations"]:
            self._add_edge(edges, scope_id, node_by_source.get(("observation", row["observation_id"])), node_by_source.get(("entity", row["entity_id"])), "SEMANTIC", "REFERS_TO", float(row.get("confidence") or 1.0), row.get("source") or "entity_observations", {"observation_id": row["observation_id"], "entity_id": row["entity_id"]}, "", f"entity_observations:{row['entity_id']}:{row['observation_id']}")
        for row in source["entity_mentions"]:
            self._add_edge(edges, scope_id, node_by_source.get(("observation", row["observation_id"])), node_by_source.get(("entity", row["entity_id"])), "SEMANTIC", "REFERS_TO", float(row.get("confidence") or 1.0), "entity_mentions", {"observation_id": row["observation_id"], "entity_id": row["entity_id"], "face_instance_id": row.get("face_instance_id")}, "", f"entity_mentions:{row['id']}")
        for row in source["event_entities"]:
            self._add_edge(edges, scope_id, node_by_source.get(("event", row["event_id"])), node_by_source.get(("entity", row["entity_id"])), "SEMANTIC", "REFERS_TO", float(row.get("confidence") or 1.0), row.get("relation") or "event_entities", {"event_id": row["event_id"], "entity_id": row["entity_id"], "evidence_ids": _loads(row.get("evidence_ids_json"), [])}, "", f"event_entities:{row['event_id']}:{row['entity_id']}:{row.get('relation')}")

        for row in source["relationships"]:
            self._add_edge(edges, scope_id, node_by_source.get(("entity", row["subject_entity_id"])), node_by_source.get(("entity", row["object_entity_id"])), "SEMANTIC", "RELATED_TO", float(row.get("confidence") or 0.0), row.get("predicate") or "", {"relationship_id": row["id"], "predicate": row.get("predicate"), "status": row.get("status"), "evidence_ids": _loads(row.get("evidence_ids_json"), [])}, self._source_row_revision(row), row["id"])

        return list(nodes.values()), list(edges.values()), source_revision

    def rebuild(self, scope_id):
        scope_id = str(scope_id or "").strip()
        if not scope_id:
            raise ValueError("scope_id is required")
        self.ensure_schema()
        build_id = f"gmb_{uuid.uuid4().hex}"
        started = _now()
        source_revision = self._source_revision(scope_id)
        try:
            self.connection.execute("BEGIN IMMEDIATE")
            self.connection.execute("DELETE FROM graph_memory_edges WHERE scope_id = ?", (scope_id,))
            self.connection.execute("DELETE FROM graph_memory_nodes WHERE scope_id = ?", (scope_id,))
            nodes, edges, source_revision = self._build_rows(scope_id)
            for node in nodes:
                now = _now()
                self.connection.execute(
                    """INSERT INTO graph_memory_nodes(
                        node_id, scope_id, node_type, source_type, source_id, title, content,
                        time_start, time_end, attributes_json, search_text, source_revision,
                        created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (node["node_id"], node["scope_id"], node["node_type"], node["source_type"], node["source_id"], node["title"], node["content"], node["time_start"], node["time_end"], node["attributes_json"], node["search_text"], node["source_revision"], now, now),
                )
            for edge in edges:
                now = _now()
                self.connection.execute(
                    """INSERT INTO graph_memory_edges(
                        edge_id, scope_id, source_node_id, target_node_id, edge_type,
                        edge_subtype, confidence, reason, attributes_json, source_revision,
                        created_at, updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (edge["edge_id"], edge["scope_id"], edge["source_node_id"], edge["target_node_id"], edge["edge_type"], edge["edge_subtype"], edge["confidence"], edge["reason"], edge["attributes_json"], edge["source_revision"], now, now),
                )
            stats = self._stats_in_transaction(scope_id)
            finished = _now()
            self.connection.execute(
                "INSERT INTO graph_memory_builds(build_id, scope_id, status, source_revision, stats_json, created_at, updated_at, finished_at) VALUES (?,?,?,?,?,?,?,?)",
                (build_id, scope_id, "completed", source_revision, _json(stats, {}), started, finished, finished),
            )
            self.connection.commit()
            stats.update({"build_id": build_id, "scope_id": scope_id, "status": "completed", "source_revision": source_revision})
            return stats
        except Exception as error:
            self.connection.rollback()
            failed_at = _now()
            try:
                self.connection.execute(
                    "INSERT INTO graph_memory_builds(build_id, scope_id, status, source_revision, stats_json, error, created_at, updated_at, finished_at) VALUES (?,?,?,?,?,?,?,?,?)",
                    (build_id, scope_id, "failed", source_revision, "{}", f"{type(error).__name__}: {error}"[:2000], started, failed_at, failed_at),
                )
                self.connection.commit()
            except Exception:
                self.connection.rollback()
            raise

    def _stats_in_transaction(self, scope_id):
        node_rows = self._rows("SELECT node_type, COUNT(*) AS count FROM graph_memory_nodes WHERE scope_id = ? GROUP BY node_type ORDER BY node_type", (scope_id,))
        edge_rows = self._rows("SELECT edge_type, edge_subtype, COUNT(*) AS count FROM graph_memory_edges WHERE scope_id = ? GROUP BY edge_type, edge_subtype ORDER BY edge_type, edge_subtype", (scope_id,))
        node_counts = {row["node_type"]: int(row["count"]) for row in node_rows}
        edge_counts = {f"{row['edge_type']}:{row['edge_subtype']}".rstrip(":"): int(row["count"]) for row in edge_rows}
        return {"nodes": sum(node_counts.values()), "edges": sum(edge_counts.values()), "node_counts": node_counts, "edge_counts": edge_counts, "causal_edges": sum(count for key, count in edge_counts.items() if key.split(":", 1)[-1] in CAUSAL_EDGE_SUBTYPES)}

    def stats(self, scope_id):
        scope_id = str(scope_id or "").strip()
        if not scope_id:
            raise ValueError("scope_id is required")
        self.ensure_schema()
        result = self._stats_in_transaction(scope_id)
        result["scope_id"] = scope_id
        result["latest_build"] = self._row("SELECT * FROM graph_memory_builds WHERE scope_id = ? ORDER BY created_at DESC LIMIT 1", (scope_id,))
        if result["latest_build"]:
            result["latest_build"]["stats"] = _loads(result["latest_build"].get("stats_json"), {})
        return result

    def _public_node(self, row, *, graph_score=None, depth=None, matched_terms=None):
        result = dict(row)
        result["attributes"] = _loads(result.pop("attributes_json", "{}"), {})
        if graph_score is not None:
            result["graph_score"] = round(float(graph_score), 6)
        if depth is not None:
            result["depth"] = int(depth)
        if matched_terms is not None:
            result["matched_terms"] = list(matched_terms)
        return result

    def get_node(self, node_id, scope_id):
        self.ensure_schema()
        row = self._row("SELECT * FROM graph_memory_nodes WHERE node_id = ? AND scope_id = ?", (str(node_id), str(scope_id)))
        return self._public_node(row) if row else None

    @staticmethod
    def _query_terms(query):
        text = str(query or "").strip().casefold()
        terms = []
        for token in re.findall(r"[\w\-]+", text, flags=re.UNICODE):
            if token and token not in terms:
                terms.append(token)
        for chunk in re.findall(r"[\u4e00-\u9fff]+", text):
            if len(chunk) >= 2:
                for index in range(len(chunk) - 1):
                    term = chunk[index:index + 2]
                    if term not in terms:
                        terms.append(term)
        return terms

    def _edge_rows_for(self, scope_id, node_id, edge_types=None, min_confidence=0.0):
        edge_types = _csv_or_list(edge_types)
        rows = self._rows(
            """SELECT * FROM graph_memory_edges
            WHERE scope_id = ? AND (source_node_id = ? OR target_node_id = ?)
              AND confidence >= ? ORDER BY edge_id""",
            (scope_id, node_id, node_id, float(min_confidence or 0)),
        )
        if edge_types:
            rows = [row for row in rows if row["edge_type"].upper() in edge_types or row["edge_subtype"].upper() in edge_types]
        return rows

    def search(self, query, scope_id, limit=8, expand_depth=2, node_types=None):
        scope_id = str(scope_id or "").strip()
        if not scope_id:
            raise ValueError("scope_id is required")
        self.ensure_schema()
        limit = max(1, min(int(limit or 8), 100))
        expand_depth = max(0, min(int(expand_depth or 0), 5))
        allowed_types = {item for item in _csv_or_list(node_types) if item in NODE_TYPES}
        terms = self._query_terms(query)
        rows = self._rows("SELECT * FROM graph_memory_nodes WHERE scope_id = ? ORDER BY node_id", (scope_id,))
        scored = []
        for row in rows:
            if allowed_types and row["node_type"] not in allowed_types:
                continue
            haystack = str(row.get("search_text") or "").casefold()
            matched = [term for term in terms if term in haystack]
            if not matched:
                continue
            exact_bonus = sum(1 for term in matched if term in haystack.split())
            score = (len(matched) / max(1, len(terms))) + exact_bonus * 0.15
            score *= DEFAULT_NODE_WEIGHTS.get(row["node_type"], 0.5)
            scored.append((score, row, matched))
        scored.sort(key=lambda item: (-item[0], item[1]["node_id"]))
        anchors = scored[:5]
        anchor_nodes = [self._public_node(row, graph_score=score, depth=0, matched_terms=matched) for score, row, matched in anchors]
        anchor_ids = {row["node_id"] for _, row, _ in anchors}
        visited = set(anchor_ids)
        expanded = {}
        queue = deque((row["node_id"], 0, score) for score, row, _ in anchors)
        while queue and len(visited) < 500:
            node_id, depth, anchor_score = queue.popleft()
            if depth >= expand_depth:
                continue
            for edge in self._edge_rows_for(scope_id, node_id):
                neighbor_id = edge["target_node_id"] if edge["source_node_id"] == node_id else edge["source_node_id"]
                if neighbor_id in visited:
                    continue
                neighbor = self._row("SELECT * FROM graph_memory_nodes WHERE node_id = ? AND scope_id = ?", (neighbor_id, scope_id))
                if not neighbor:
                    continue
                if allowed_types and neighbor["node_type"] not in allowed_types:
                    continue
                visited.add(neighbor_id)
                next_depth = depth + 1
                graph_score = anchor_score * (0.75 ** next_depth) * float(edge.get("confidence") or 0.0) * DEFAULT_NODE_WEIGHTS.get(neighbor["node_type"], 0.5)
                expanded[neighbor_id] = (graph_score, next_depth, neighbor, edge)
                queue.append((neighbor_id, next_depth, anchor_score))
        expanded_rows = [self._public_node(row, graph_score=score, depth=depth) for score, depth, row, _ in expanded.values()]
        expanded_rows.sort(key=lambda item: (-item.get("graph_score", 0), item["node_id"]))
        return {
            "query": str(query or ""), "scope_id": scope_id, "matched_terms": terms,
            "anchors": anchor_nodes, "expanded": expanded_rows,
            "results": anchor_nodes[:limit] + expanded_rows[: max(0, limit - len(anchor_nodes))],
            "graph_score": round(max((item[0] for item in anchors), default=0.0), 6),
            "depth": expand_depth,
        }

    def subgraph(self, node_id, scope_id, max_depth=2, max_nodes=500, edge_types=None, min_confidence=0.0):
        scope_id = str(scope_id or "").strip()
        max_depth = max(0, min(int(max_depth or 0), 5))
        max_nodes = max(1, min(int(max_nodes or 500), 500))
        self.ensure_schema()
        root = self._row("SELECT * FROM graph_memory_nodes WHERE node_id = ? AND scope_id = ?", (node_id, scope_id))
        if not root:
            return None
        nodes = {node_id: (root, 0)}
        edges = {}
        queue = deque([(node_id, 0)])
        while queue and len(nodes) < max_nodes:
            current, depth = queue.popleft()
            if depth >= max_depth:
                continue
            for edge in self._edge_rows_for(scope_id, current, edge_types, min_confidence):
                edges[edge["edge_id"]] = edge
                neighbor_id = edge["target_node_id"] if edge["source_node_id"] == current else edge["source_node_id"]
                if neighbor_id in nodes:
                    continue
                row = self._row("SELECT * FROM graph_memory_nodes WHERE node_id = ? AND scope_id = ?", (neighbor_id, scope_id))
                if row:
                    nodes[neighbor_id] = (row, depth + 1)
                    queue.append((neighbor_id, depth + 1))
                    if len(nodes) >= max_nodes:
                        break
        public_edges = []
        for edge in edges.values():
            item = dict(edge)
            item["attributes"] = _loads(item.pop("attributes_json", "{}"), {})
            public_edges.append(item)
        return {
            "scope_id": scope_id, "root_node_id": node_id,
            "nodes": [self._public_node(row, depth=depth) for row, depth in nodes.values()],
            "edges": public_edges,
        }
